---
abstract: 'stream and data flow handling for async code'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Log::Any::Adapter: '1.045'
  Log::Any::Adapter::TAP: '0.003002'
  Test::CheckDeps: '0.010'
  Test::Deep: '1.124'
  Test::Fatal: '0.010'
  Test::Files: '0.14'
  Test::More: '0.98'
  Test::Refcount: '0.07'
  Test::Warnings: '0.024'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Ryu
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Ryu:
    file: lib/Ryu.pm
    version: '0.036'
  Ryu::Buffer:
    file: lib/Ryu/Buffer.pm
    version: '0.036'
  Ryu::Exception:
    file: lib/Ryu/Exception.pm
    version: '0.036'
  Ryu::Node:
    file: lib/Ryu/Node.pm
    version: '0.036'
  Ryu::Observable:
    file: lib/Ryu/Observable.pm
    version: '0.036'
  Ryu::Sink:
    file: lib/Ryu/Sink.pm
    version: '0.036'
  Ryu::Source:
    file: lib/Ryu/Source.pm
    version: '0.036'
  Ryu::Stream:
    file: lib/Ryu/Stream.pm
    version: '0.036'
recommends:
  JSON::MaybeUTF8: '1.000'
  MIME::Base64: '0'
  Text::CSV: '0'
requires:
  Encode: '1.98'
  Exporter: '0'
  Future: '0.37'
  JSON::MaybeXS: '0'
  List::Util: '0'
  List::UtilsBy: '0.10'
  Log::Any: '1.045'
  Log::Any::Adapter: '1.045'
  MIME::Base64: '0'
  Ref::Util: '0.111'
  Scalar::Util: '1.47'
  Syntax::Keyword::Try: '0.04'
  Text::CSV: '0'
  Variable::Disposition: '0.004'
  curry: '1.001'
  curry::weak: '0'
  indirect: '0'
  namespace::clean: '0.27'
  overload: '0'
  parent: '0'
  sort: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Ryu/issues
  homepage: https://github.com/team-at-cpan/Ryu
  repository: https://github.com/team-at-cpan/Ryu.git
version: '0.036'
x_authority: cpan:TEAM
x_contributors:
  - 'Amin Marashi <marashi.s.amin@gmail.com>'
  - 'tm604 <tom@perlsite.co.uk>'
x_generated_by_perl: v5.28.1
x_serialization_backend: 'YAML::Tiny version 1.73'
